// Filosofia de design: Modernismo Suíço Executivo. As páginas internas preservam clareza editorial, diagnóstico objetivo, prova contextual e conversão consultiva.
/*
 * Modernismo Suíço Executivo: páginas por segmento mantêm linguagem consultiva, grelha precisa,
 * contraste institucional e logomarca oficial Vision como âncora de confiança em navegação e fechamento.
 */
import { ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, CheckCircle2, ClipboardList, Factory, Gauge, LineChart, Network, PieChart, ShieldCheck, Target, Users } from "lucide-react";

const VISION_LOGO = "https://visionnovo.manus.space/manus-storage/Vision-logomarca_a0c5239c.png";
const SEGMENTS_IMAGE = "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=85";
const PLATFORM_IMAGE = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85";
const METHOD_IMAGE = "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1400&q=85";

type IconType = typeof Target;
type Segment = { slug: string; title: string; eyebrow: string; headline: string; intro: string; clients: string[]; context: string; pains: string[]; visionAnswer: string; solutions: { title: string; text: string; icon: IconType }[]; outcomes: string[]; roadmap: { step: string; title: string; text: string }[]; proof: string; conversion: string; icon: IconType };

const segmentData: Segment[] = [
  { slug: "provedores-e-telecom", title: "Provedores e telecom", eyebrow: "Gestão para redes em expansão", headline: "Crescer em telecom exige processos, indicadores e decisões comerciais com margem sob controle.", intro: "A Vision apoia provedores, empresas de conectividade e operações de telecom na transição de uma gestão reativa para um modelo orientado por dados, rotina, atendimento e expansão sustentável.", clients: ["Smart", "NV7", "Resolve", "Net Planet", "Network", "MP Telecom", "NC Telecon", "Conect Mais", "Zavaz", "Microrcim", "Conecta", "Sofway", "GTBA", "Next", "Veloznet"], context: "O setor combina pressão por atendimento, expansão regional, competição por preço, custos técnicos e necessidade de profissionalização da liderança. Sem método, a operação cresce, mas a gestão perde visibilidade.", pains: ["Expansão comercial sem leitura clara de margem e capacidade operacional.", "Atendimento e suporte técnico dependentes de pessoas, e não de processos.", "Indicadores dispersos entre financeiro, comercial e operação.", "Dificuldade em priorizar investimentos em rede, equipe e tecnologia."], visionAnswer: "A resposta da Vision integra estratégia de negócio, processos eficazes, inteligência financeira e Aigest - Plataforma de Gestão para transformar crescimento em previsibilidade.", solutions: [{ title: "Estratégia de Negócio", text: "Define direção, metas, prioridades regionais, posicionamento e plano tático para expansão.", icon: Target }, { title: "Processos Eficazes", text: "Padroniza atendimento, instalação, suporte, rotinas técnicas e fluxos internos.", icon: ClipboardList }, { title: "Inteligência Financeira", text: "Organiza orçamento, fluxo de caixa, metas, rentabilidade e decisões de investimento.", icon: PieChart }, { title: "Aigest - Plataforma de Gestão", text: "Consolida indicadores para acompanhamento contínuo da operação e tomada de decisão.", icon: BarChart3 }], outcomes: ["Indicadores de expansão e rentabilidade acompanháveis.", "Rotinas técnicas e comerciais mais previsíveis.", "Decisões de investimento com base em dados.", "Gestão preparada para escala regional."], roadmap: [{ step: "01", title: "Diagnóstico de rede e gestão", text: "Leitura integrada de operação, atendimento, vendas, financeiro e liderança." }, { step: "02", title: "Priorização de gargalos", text: "Identificação dos pontos que mais afetam margem, satisfação e capacidade de crescimento." }, { step: "03", title: "Estruturação de rotinas", text: "Desenho de processos, indicadores, responsáveis e cadência de gestão." }, { step: "04", title: "Acompanhamento executivo", text: "Reuniões de evolução e ajustes para manter o plano vivo." }], proof: "Clientes do universo de provedores e telecom já aparecem entre os nomes atendidos pela Vision, reforçando experiência em operações de conectividade.", conversion: "Solicite um diagnóstico para entender onde a gestão do provedor precisa ganhar previsibilidade antes da próxima fase de expansão.", icon: Network },
  { slug: "industria-e-operacoes", title: "Indústria e operações", eyebrow: "Produtividade com método", headline: "Operações industriais precisam transformar rotina, custo e produtividade em gestão visível.", intro: "A Vision ajuda empresas industriais e operações intensivas a organizarem processos, indicadores, responsabilidades e finanças para reduzir improvisos e aumentar previsibilidade.", clients: ["Meira Diesel", "Norte de Minas"], context: "Em ambientes operacionais, pequenas ineficiências acumuladas afetam prazo, custo, qualidade e margem. O desafio não é apenas produzir mais, mas gerir melhor o fluxo que sustenta a entrega.", pains: ["Processos produtivos pouco documentados ou dependentes de experiência individual.", "Dificuldade em medir produtividade, retrabalho, custos e capacidade.", "Organograma e responsabilidades sem clareza suficiente.", "Decisões operacionais desconectadas do orçamento e da estratégia."], visionAnswer: "A Vision conecta processos eficazes, inteligência financeira e gestão por indicadores para tornar a operação mensurável, padronizada e preparada para crescimento.", solutions: [{ title: "Processos Eficazes", text: "Mapeia cadeia de valor, fluxos, POPs, não conformidades e pontos de controle.", icon: ClipboardList }, { title: "Inteligência Financeira", text: "Relaciona custos, orçamento, metas e fluxo de caixa à realidade operacional.", icon: PieChart }, { title: "Pessoas Excelentes", text: "Apoia liderança, responsabilidades, desempenho e desenvolvimento de equipes.", icon: Users }, { title: "Gestão por Indicadores", text: "Cria painéis e rituais para acompanhar produtividade e evolução.", icon: LineChart }], outcomes: ["Operação documentada e menos dependente de improviso.", "Custos e produtividade acompanhados com método.", "Responsabilidades mais claras entre áreas.", "Decisões operacionais alinhadas à estratégia."], roadmap: [{ step: "01", title: "Mapear fluxo operacional", text: "Compreensão da cadeia de valor, rotinas, gargalos e responsabilidades." }, { step: "02", title: "Definir indicadores críticos", text: "Escolha dos KPIs que mostram produtividade, custo, qualidade e prazo." }, { step: "03", title: "Padronizar execução", text: "Documentação de processos, POPs e acordos de gestão entre áreas." }, { step: "04", title: "Medir e ajustar", text: "Acompanhamento periódico para melhoria contínua e tomada de decisão." }], proof: "A presença de clientes operacionais e industriais no portfólio atual permite posicionar a Vision como parceira de profissionalização da gestão produtiva.", conversion: "Agende um diagnóstico para identificar onde processos, custos e indicadores podem gerar ganhos práticos de desempenho.", icon: Factory },
  { slug: "saude-e-cuidado", title: "Saúde e cuidado", eyebrow: "Gestão para qualidade e experiência", headline: "Organizações de saúde precisam equilibrar cuidado, padrão de atendimento, equipe e sustentabilidade financeira.", intro: "A Vision ajuda clínicas, serviços de cuidado e organizações relacionadas a profissionalizarem processos, liderança, indicadores e rotina financeira sem perder a sensibilidade do atendimento.", clients: ["Clinort", "Cuidar", "Centro Oftalmológico Norte de Minas"], context: "A operação de saúde exige confiança, qualidade, rotina, conformidade e experiência. Quando processos e indicadores são frágeis, a percepção do cliente e a sustentabilidade do negócio ficam vulneráveis.", pains: ["Atendimento e jornada do paciente pouco padronizados.", "Equipes com responsabilidades e critérios de desempenho pouco claros.", "Indicadores assistenciais, comerciais e financeiros desconectados.", "Dificuldade em manter qualidade enquanto a operação cresce."], visionAnswer: "A Vision combina processos, pessoas, finanças e Aigest - Plataforma de Gestão para dar clareza à operação e apoiar decisões que preservam qualidade e resultado.", solutions: [{ title: "Processos Eficazes", text: "Padroniza atendimento, jornada, retaguarda administrativa e fluxos críticos.", icon: ClipboardList }, { title: "Pessoas Excelentes", text: "Apoia liderança, cultura de atendimento, desempenho e desenvolvimento.", icon: Users }, { title: "Inteligência Financeira", text: "Organiza custos, metas, orçamento e previsibilidade de caixa.", icon: PieChart }, { title: "Aigest - Plataforma de Gestão", text: "Acompanha indicadores de operação, equipe, finanças e experiência.", icon: BarChart3 }], outcomes: ["Jornada de atendimento mais padronizada.", "Indicadores para qualidade e gestão financeira.", "Equipes com papéis e rotinas mais claros.", "Crescimento com preservação da experiência do cliente."], roadmap: [{ step: "01", title: "Diagnosticar jornada e operação", text: "Leitura dos pontos de contato, processos internos, equipe e finanças." }, { step: "02", title: "Definir padrões de gestão", text: "Criação de critérios, indicadores e rotinas de acompanhamento." }, { step: "03", title: "Desenvolver equipe e liderança", text: "Ajustes de papéis, comunicação e cultura de atendimento." }, { step: "04", title: "Acompanhar resultados", text: "Ciclos de revisão para ajustar experiência, produtividade e sustentabilidade." }], proof: "Clientes como Clinort, Cuidar e Centro Oftalmológico Norte de Minas demonstram aderência da Vision a segmentos nos quais qualidade, processo e confiança caminham juntos.", conversion: "Agende um diagnóstico para compreender onde a operação de saúde pode ganhar clareza sem perder cuidado e proximidade.", icon: ShieldCheck },
  { slug: "varejo-moveis-e-distribuicao", title: "Varejo, móveis e distribuição", eyebrow: "Margem, estoque e rotina comercial", headline: "Varejo e distribuição precisam transformar velocidade comercial em controle de margem, estoque e atendimento.", intro: "A Vision apoia negócios de varejo, móveis e distribuição na organização de processos, finanças, pessoas e indicadores para vender melhor sem perder controle operacional.", clients: ["Diniz", "Faria Store", "JB Móveis"], context: "Empresas comerciais vivem pressão por preço, giro, atendimento e caixa. Crescer sem leitura de margem, estoque e rotina faz com que vendas aumentem sem necessariamente gerar resultado sustentável.", pains: ["Margem, estoque e fluxo de caixa acompanhados de forma fragmentada.", "Equipe comercial sem rotina clara de meta e atendimento.", "Processos de compra, venda e pós-venda pouco documentados.", "Decisões de promoção e expansão sem visão financeira completa."], visionAnswer: "A Vision estrutura inteligência financeira, processos e pessoas para tornar a operação comercial mais previsível, orientada a metas e conectada ao resultado.", solutions: [{ title: "Inteligência Financeira", text: "Integra fluxo de caixa, orçamento, metas, margem e decisões comerciais.", icon: PieChart }, { title: "Processos Eficazes", text: "Organiza compra, venda, estoque, entrega, atendimento e pós-venda.", icon: ClipboardList }, { title: "Pessoas Excelentes", text: "Desenvolve liderança, equipe de vendas e cultura de performance.", icon: Users }, { title: "Gestão por Indicadores", text: "Acompanha giro, margem, ticket, produtividade e satisfação.", icon: Gauge }], outcomes: ["Maior clareza sobre margem e caixa.", "Rotina comercial mais disciplinada.", "Processos de venda e entrega mais consistentes.", "Decisões de estoque e promoção com menos improviso."], roadmap: [{ step: "01", title: "Analisar operação comercial", text: "Leitura de vendas, atendimento, estoque, caixa, equipe e margem." }, { step: "02", title: "Definir metas e indicadores", text: "Escolha dos números que devem orientar rotina e decisão." }, { step: "03", title: "Padronizar processos críticos", text: "Organização de fluxos de compra, venda, entrega e pós-venda." }, { step: "04", title: "Implantar cadência de gestão", text: "Acompanhamento de metas, planos de ação e ajustes comerciais." }], proof: "A presença de marcas de varejo e móveis no portfólio atual permite criar uma narrativa específica para empresas comerciais que precisam crescer com controle.", conversion: "Solicite uma avaliação para identificar onde margem, estoque, equipe e rotina comercial podem gerar resultado mais previsível.", icon: Gauge },
  { slug: "alimentos-e-operacao-recorrente", title: "Alimentos", eyebrow: "Padronização, custo e qualidade", headline: "Operações de alimentos precisam controlar padrão, custo e produtividade todos os dias.", intro: "A Vision apoia empresas de alimentos e negócios com alta repetição operacional na estruturação de processos, custos, qualidade e indicadores.", clients: ["Uvale", "Ayê", "Extra Distribuidora de Bebidas"], context: "Em operações de alimentos, resultado sustentável depende da disciplina diária. Pequenas variações de processo, custo, desperdício e qualidade podem comprometer margem e experiência do cliente.", pains: ["Custos e desperdícios pouco visíveis na rotina.", "Processos de produção, atendimento ou entrega sem padrão consistente.", "Dificuldade em medir qualidade, produtividade e margem.", "Crescimento baseado em esforço operacional, não em método."], visionAnswer: "A Vision estrutura processos eficazes, inteligência financeira e Aigest - Plataforma de Gestão para criar rotina, padronização e acompanhamento contínuo de resultados.", solutions: [{ title: "Processos Eficazes", text: "Mapeia fluxos, documenta padrões e reduz variações operacionais.", icon: ClipboardList }, { title: "Inteligência Financeira", text: "Acompanha custos, orçamento, metas, margem e fluxo de caixa.", icon: PieChart }, { title: "Pessoas Excelentes", text: "Alinha equipe, liderança, rotina e cultura de qualidade.", icon: Users }, { title: "Aigest - Plataforma de Gestão", text: "Dá visibilidade aos indicadores críticos da operação recorrente.", icon: BarChart3 }], outcomes: ["Padrões de execução mais consistentes.", "Custos e desperdícios acompanhados com clareza.", "Indicadores de produtividade e qualidade visíveis.", "Rotina preparada para expansão controlada."], roadmap: [{ step: "01", title: "Mapear rotina recorrente", text: "Leitura dos processos, custos, qualidade, equipe e pontos de perda." }, { step: "02", title: "Priorizar padrões críticos", text: "Definição dos processos que mais afetam margem e experiência." }, { step: "03", title: "Implantar indicadores", text: "Criação de números de acompanhamento para custo, produtividade e qualidade." }, { step: "04", title: "Ajustar em ciclos", text: "Melhoria contínua com reuniões de gestão e planos de ação." }], proof: "Clientes como Uvale, Ayê e Extra Distribuidora de Bebidas reforçam o posicionamento da Vision em operações recorrentes que dependem de padrão, custo e qualidade.", conversion: "Solicite um diagnóstico para avaliar como padronização, custos e indicadores podem aumentar previsibilidade operacional.", icon: BarChart3 },
];

function getCurrentSegment() { const slug = window.location.pathname.split("/").filter(Boolean).pop() ?? "provedores-e-telecom"; return segmentData.find((segment) => segment.slug === slug); }
function scrollTop() { window.scrollTo({ top: 0, behavior: "smooth" }); }

export default function SegmentPage() {
  const segment = getCurrentSegment();
  if (!segment) {
    return (
      <div className="min-h-screen bg-background text-foreground selection:bg-[#189cd9]/20 selection:text-[#373d43]">
        <main className="container grid min-h-screen place-items-center py-24 text-center">
          <div className="max-w-2xl border border-[#373d43]/12 bg-white p-10 shadow-xl">
            <p className="eyebrow">Segmento não disponível</p>
            <h1 className="mt-4 font-display text-5xl font-semibold tracking-[-0.05em] text-[#373d43]">Esta página de segmento foi removida.</h1>
            <p className="mt-5 leading-8 text-[#9b9b9b]">A Vision reorganizou seus segmentos prioritários. Volte para a página inicial para consultar as soluções atualmente apresentadas.</p>
            <a href="/#segmentos" className="btn-primary mt-8">Voltar aos segmentos</a>
          </div>
        </main>
      </div>
    );
  }
  const Icon = segment.icon;
  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-[#189cd9]/20 selection:text-[#373d43]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-[#373d43]/10 bg-[#FFFFFF]/90 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between gap-6"><a href="/" className="group flex items-center" aria-label="Vision Consultores"><img src={VISION_LOGO} alt="Vision Consultores" className="h-12 w-auto max-w-[172px] object-contain transition duration-300 group-hover:opacity-85 sm:h-14" /></a><nav className="hidden items-center gap-7 lg:flex" aria-label="Navegação de segmentos"><a href="/#metodo" className="text-sm font-medium text-[#373d43] transition hover:text-[#373d43]">Método</a><a href="/#solucoes" className="text-sm font-medium text-[#373d43] transition hover:text-[#373d43]">Soluções</a><a href="/#segmentos" className="text-sm font-medium text-[#373d43] transition hover:text-[#373d43]">Segmentos</a><a href="#diagnostico" className="text-sm font-medium text-[#373d43] transition hover:text-[#373d43]">Diagnóstico</a></nav><a href="#diagnostico" className="btn-primary hidden lg:inline-flex">Agendar diagnóstico</a></div></header>
      <main>
        <section className="relative overflow-hidden pt-28 lg:pt-32"><div className="absolute inset-0 swiss-grid opacity-70" /><div className="container relative grid min-h-[650px] items-center gap-10 py-12 lg:grid-cols-[0.96fr_1.04fr] lg:py-16"><div><a href="/#segmentos" className="inline-flex items-center gap-2 text-sm font-semibold text-[#373d43] transition hover:text-[#373d43]"><ArrowLeft className="size-4" /> Voltar aos segmentos</a><p className="eyebrow mt-10">{segment.eyebrow}</p><h1 className="mt-6 font-display text-5xl font-semibold leading-[0.96] tracking-[-0.055em] text-[#373d43] sm:text-6xl lg:text-7xl">{segment.headline}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#373d43] sm:text-xl">{segment.intro}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#diagnostico" className="btn-primary group">Solicitar diagnóstico <ArrowRight className="size-4 transition group-hover:translate-x-1" /></a><a href="#resposta" className="btn-secondary">Ver resposta Vision</a></div></div><div className="relative min-h-[420px]"><div className="absolute inset-x-0 top-8 h-[82%] bg-[#373d43] shadow-2xl lg:-right-20 lg:left-8" /><img src={SEGMENTS_IMAGE} alt={`Equipe corporativa em planejamento estratégico para ${segment.title}`} className="relative ml-auto h-[520px] w-full object-cover shadow-[0_32px_80px_rgba(55,61,67,0.28)]" /><div className="absolute bottom-4 left-0 max-w-sm border border-white/30 bg-[#FFFFFF]/94 p-6 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center bg-[#373d43] text-[#FFFFFF]"><Icon className="size-6" /></span><p className="font-display text-2xl font-semibold leading-tight text-[#373d43]">{segment.title}</p></div><p className="mt-4 leading-7 text-[#9b9b9b]">{segment.context}</p></div></div></div></section>
        <section className="border-y border-[#373d43]/10 bg-[#373d43] py-7 text-[#FFFFFF]"><div className="container grid gap-5 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><p className="font-display text-2xl font-semibold">Clientes neste segmento.</p><div className="flex flex-wrap gap-2">{segment.clients.map((client) => <span key={client} className="border border-white/12 bg-white/8 px-3 py-2 text-sm font-semibold text-[#FFFFFF]">{client}</span>)}</div></div></section>
        <section className="container py-24"><div className="grid gap-10 lg:grid-cols-[0.78fr_1.22fr]"><div><p className="eyebrow">Desafios do segmento</p><h2 className="section-title mt-4">O crescimento só sustenta resultado quando a gestão enxerga a operação.</h2><p className="mt-6 text-lg leading-8 text-[#9b9b9b]">{segment.context}</p><img src={METHOD_IMAGE} alt="Consultores aplicando diagnóstico estratégico em ambiente corporativo" className="mt-9 aspect-[3/2] w-full object-cover shadow-xl" /></div><div className="grid gap-4 md:grid-cols-2">{segment.pains.map((pain, index) => <article key={pain} className="border border-[#373d43]/12 bg-white p-6 shadow-[0_18px_55px_rgba(55,61,67,0.07)] transition duration-300 hover:-translate-y-1 hover:shadow-xl"><span className="font-mono text-sm text-[#189cd9]">0{index + 1}</span><p className="mt-6 font-display text-2xl font-semibold leading-tight text-[#373d43]">{pain}</p></article>)}</div></div></section>
        <section id="resposta" className="bg-[#cbe9f6] py-24"><div className="container"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="eyebrow">Resposta Vision</p><h2 className="section-title mt-4">Uma combinação de soluções para transformar diagnóstico em decisão.</h2></div><p className="max-w-3xl text-lg leading-8 text-[#9b9b9b]">{segment.visionAnswer}</p></div><div className="mt-12 grid gap-5 lg:grid-cols-4">{segment.solutions.map((solution) => { const SolutionIcon = solution.icon; return <article key={solution.title} className="service-card"><SolutionIcon className="size-7 text-[#189cd9]" /><h3 className="mt-8 font-display text-3xl font-semibold leading-tight tracking-tight text-[#373d43]">{solution.title}</h3><p className="mt-5 leading-7 text-[#9b9b9b]">{solution.text}</p></article>; })}</div></div></section>
        <section className="container py-24"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><p className="eyebrow">Método aplicado</p><h2 className="section-title mt-4">Da leitura do problema à rotina de acompanhamento.</h2><p className="mt-6 text-lg leading-8 text-[#9b9b9b]">A página interna reforça a lógica consultiva da Vision: antes de vender uma solução isolada, o processo identifica prioridades, estrutura execução e mede evolução.</p></div><div className="grid gap-4">{segment.roadmap.map((item) => <article key={item.step} className="grid gap-5 border border-[#373d43]/12 bg-white p-6 shadow-sm md:grid-cols-[80px_1fr]"><span className="font-mono text-lg font-semibold text-[#189cd9]">{item.step}</span><div><h3 className="font-display text-3xl font-semibold text-[#373d43]">{item.title}</h3><p className="mt-2 leading-7 text-[#9b9b9b]">{item.text}</p></div></article>)}</div></div></section>
        <section className="overflow-hidden bg-[#373d43] py-24 text-[#FFFFFF]"><div className="container grid gap-12 lg:grid-cols-[0.92fr_1.08fr] lg:items-center"><div><p className="eyebrow-dark">Resultados esperados</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight tracking-[-0.04em] sm:text-5xl">O objetivo é criar gestão que possa ser acompanhada, discutida e melhorada.</h2><p className="mt-6 text-lg leading-8 text-[#cbe9f6]">{segment.proof}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{segment.outcomes.map((outcome) => <div key={outcome} className="flex gap-3 border border-white/12 bg-white/6 p-4 text-sm font-medium text-[#FFFFFF]"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#cbe9f6]" />{outcome}</div>)}</div></div><div className="relative"><div className="absolute -inset-5 border border-white/10" /><img src={PLATFORM_IMAGE} alt="Profissionais analisando indicadores de gestão e dados executivos" className="relative aspect-video w-full object-cover shadow-[0_32px_90px_rgba(0,0,0,0.35)]" /><div className="relative -mt-8 ml-8 max-w-lg bg-[#FFFFFF] p-6 text-[#373d43] shadow-2xl"><p className="font-display text-2xl font-semibold">Sem dados, não há decisão consistente.</p><p className="mt-3 leading-7 text-[#9b9b9b]">A plataforma e os rituais de gestão tornam a evolução do segmento visível para líderes e equipes.</p></div></div></div></section>
        <section id="diagnostico" className="container py-24"><div className="grid overflow-hidden border border-[#373d43]/12 bg-[#373d43] lg:grid-cols-[0.88fr_1.12fr]"><div className="p-8 text-[#FFFFFF] sm:p-12 lg:p-14"><p className="eyebrow-dark">Diagnóstico por segmento</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight tracking-[-0.04em] sm:text-5xl">{segment.conversion}</h2><p className="mt-6 leading-8 text-[#cbe9f6]">A conversa inicial deve identificar estágio de gestão, gargalos, prioridades e oportunidades de ganho prático para o negócio.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/#contato" className="btn-primary bg-[#FFFFFF] text-[#373d43] shadow-[6px_6px_0_#189cd9] hover:bg-white">Usar formulário principal</a><button onClick={scrollTop} className="btn-secondary border-white/20 bg-white/5 text-[#FFFFFF] hover:bg-white/10">Rever página</button></div></div><div className="bg-[#FFFFFF] p-8 sm:p-12 lg:p-14"><p className="eyebrow">Antes da reunião</p><h3 className="mt-4 font-display text-4xl font-semibold leading-tight text-[#373d43]">Três perguntas que qualificam o diagnóstico.</h3><div className="mt-8 grid gap-4">{["Quais decisões hoje dependem mais de feeling do que de dados?", "Quais processos travam crescimento, margem ou atendimento?", "Quais indicadores precisam estar visíveis para liderar melhor?"].map((question, index) => <div key={question} className="border-l-2 border-[#189cd9] bg-white p-5"><span className="font-mono text-sm text-[#189cd9]">0{index + 1}</span><p className="mt-2 font-display text-2xl font-semibold leading-tight text-[#373d43]">{question}</p></div>)}</div></div></div></section>
      </main>
      <footer className="border-t border-[#373d43]/10 bg-[#cbe9f6] py-10">
        <div className="container flex flex-col gap-6 text-sm text-[#9b9b9b] lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-4">
            <img src={VISION_LOGO} alt="Vision Consultores" className="h-10 w-auto max-w-[150px] object-contain" />
            <p>Visão, método e decisão para {segment.title.toLowerCase()}.</p>
          </div>
          <a href="/#contato" className="font-bold uppercase tracking-[0.18em] text-[#189cd9] transition hover:text-[#373d43]">Falar com a Vision</a>
        </div>
      </footer>
    </div>
  );
}
